#!/usr/bin/env python3
"""
Royal Render pre-script helper:
- Queries the job's rrEnvList (customData_Str("rrEnvList"))
- Exports env vars as shell `export KEY=...` lines (stdout)
- Writes the same exports to: /tmp/rr/rr_env-$RR_JID.sh
- Focuses on AYON_* vars by default, but also preserves "GID stuff"
  (RR_GID / RR_GROUPID / GID / *GID* if present on the job or current env)

Typical usage in RR pre-script (bash):
  rrpython get_envs.py -jid "$RR_JID"
  source "/tmp/rr/rr_env-$RR_JID.sh"

Or (if you prefer not to source a file):
  eval "$(rrpython get_envs.py -jid "$RR_JID" --stdout-only)"
"""

import argparse
import os
import sys
from pathlib import Path


def _rr_sdk_import():
    rr_root = os.environ.get("RR_ROOT")
    if not rr_root:
        raise RuntimeError("RR_ROOT is not set")

    mod_dir = os.path.join(rr_root, "SDK", "External", "Python")
    if mod_dir not in sys.path:
        sys.path.append(mod_dir)

    import rr_python_utils.connection as rr_connect  # noqa: E402

    return rr_connect


def _sh_quote(value: str) -> str:
    """
    POSIX-safe single-quote quoting.
    Turns: abc'def  ->  'abc'"'"'def'
    """
    if value is None:
        value = ""
    value = str(value)
    return "'" + value.replace("'", "'\"'\"'") + "'"


def _parse_rr_env_list(rr_env_list: str) -> dict:
    """
    rrEnvList format typically: KEY=VALUE~~~KEY2=VALUE2~~~...
    """
    envs = {}
    if not rr_env_list:
        return envs

    for chunk in rr_env_list.split("~~~"):
        if not chunk.strip():
            continue
        if "=" not in chunk:
            # Skip malformed entries
            continue
        key, value = chunk.split("=", 1)
        key = key.strip()
        if not key:
            continue
        envs[key] = value
    return envs


def _connect_and_get_job(rr_connect, jid: int):
    tcp = rr_connect.server_connect(user_name=None)
    tcp.configGetGlobal()
    if tcp.errorMessage():
        raise RuntimeError(tcp.errorMessage())

    if not tcp.jobList_GetInfo(int(jid)):
        raise RuntimeError("jobList_GetInfo failed: " + tcp.errorMessage())

    job = tcp.jobs.getJobSend(int(jid))

    # Ensure paths match job OS (not strictly needed for rrEnvList, but harmless)
    try:
        tcp.jobs.setPathTargetOS(job.sceneOS)
    except Exception:
        pass

    return job


def _is_gid_var(name: str) -> bool:
    u = name.upper()
    if u in {"GID", "RR_GID", "RR_GROUPID", "RR_GROUP_ID"}:
        return True
    # "Keep GID stuff" more broadly (covers things like SOMETHING_GID)
    return "GID" in u


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-jid", required=False, help="Royal Render Job ID")
    parser.add_argument(
        "--stdout-only",
        action="store_true",
        help="Only print export lines to stdout; do not write /tmp/rr/rr_env-$RR_JID.sh",
    )
    parser.add_argument(
        "--include-all",
        action="store_true",
        help="Export all rrEnvList entries (not only AYON_* plus GID stuff).",
    )
    args = parser.parse_args()

    jid = args.jid or os.environ.get("RR_JID")
    if not jid:
        raise RuntimeError("Missing job id. Provide -jid or set RR_JID.")
    try:
        jid_int = int(jid)
    except ValueError:
        raise RuntimeError(f"Invalid jid: {jid!r}")

    rr_connect = _rr_sdk_import()
    job = _connect_and_get_job(rr_connect, jid_int)

    rr_env_list = ""
    try:
        rr_env_list = job.customData_Str("rrEnvList")
    except Exception as exc:
        raise RuntimeError(f"Could not read rrEnvList from job: {exc}")

    job_envs = _parse_rr_env_list(rr_env_list)

    # Build exports:
    # - AYON_* (default) OR everything (if --include-all)
    # - plus "GID stuff" from job envs and also current shell env (if present)
    exports = {}

    if args.include_all:
        exports.update(job_envs)
    else:
        for k, v in job_envs.items():
            if k.startswith("AYON_") or _is_gid_var(k):
                exports[k] = v

    # Preserve any existing GID-ish vars already in the worker env (if not in job envs)
    for k, v in os.environ.items():
        if _is_gid_var(k) and k not in exports:
            exports[k] = v

    # Write out shell exports
    lines = []
    lines.append("#!/usr/bin/env bash")
    lines.append(f"# Auto-generated by get_envs.py for RR_JID={jid_int}")
    lines.append("set -e")
    lines.append("")

    for key in sorted(exports.keys()):
        val = exports[key]
        lines.append(f"export {key}={_sh_quote(val)}")

    lines.append("")

    # Always print to stdout so the caller can eval it if they want
    stdout_payload = "\n".join(lines)
    print(stdout_payload)

    if args.stdout_only:
        return

    out_dir = Path("/tmp/rr")
    out_dir.mkdir(parents=True, exist_ok=True)

    out_path = out_dir / f"rr_env-{jid_int}.sh"
    out_path.write_text(stdout_payload, encoding="utf-8")

    # Make it readable + sourceable
    try:
        out_path.chmod(0o644)
    except Exception:
        pass


if __name__ == "__main__":
    main()
